### ISSUE TITLE
No docker image for scheduler

### ISSUE THREAD

**Issue by philwinder** [mesos/kibana#10]
Create a docker image for the scheduler jar.

**Comment by sadovnikov** [comment]
Is there a need for this image?

**Comment by philwinder** [comment]
Yes. If not, it adds complexity to the run command and users might not have java/mesos/a dependency installed on their system. Plus it fits with our 'container first' strategy.

**Comment by luhkevin** [comment]
Is there any progress for a docker image for mesos/kibana?

**Comment by philwinder** [comment]
Started work on Kibana on Friday. Refactoring to use
containersolutions/mesos-starter. Should be ready to release new version
end of next week.

Stay tuned!
Phil
