### ISSUE TITLE
Cannot override executor docker image

### ISSUE THREAD

**Issue by micahlmartin** [mesos/kibana#15]
I'm trying to pass in these variables (https://github.com/mesos/kibana/blob/master/src/main/java/org/apache/mesos/kibana/scheduler/SchedulerConfiguration.java#L29-L30) to the jar but it doesn't like the. It's telling me I have invalid params. Here is my run command:

```
$(pwd)/jre*/bin/java -jar kibana-*.jar -zk zk://master.mesos:2181/mesos -p 9001 -cpu 0.1 -mem 64.0 -disk 25 -di mydocker/kibana -v 4.4
```

Any idea what's happening here?

**Comment by sadovnikov** [comment]
Where are your `kibana-*.jar` files from? Have you taken them from https://github.com/mesos/kibana/releases/tag/0.3.2 ?
