### ISSUE TITLE
Mesos Framework Authentication

### ISSUE THREAD

**Issue by akamalov** [mesos/kibana#24]
Hello, 

Just wondering if current mesos/kibana supports Mesos framework authentication?

Thank you,

Alex

**Comment by philwinder** [comment]
Yes it does. Please see the main page documentation: https://github.com/mesos/kibana

**Comment by philwinder** [comment]
@akamalov I think you replied to the wrong message.

Ah, I'm so sorry. I thought I had added that to the documentation, but I have not. The options come from mesos-starter: https://github.com/ContainerSolutions/mesos-starter/tree/documentation/readme#configuration

So the option you are looking for is: `mesos.principal` and `mesos.secret`. I will add this to the documentation now.

Thanks.

**Comment by akamalov** [comment]
Thanks so much @philwinder
