### ISSUE TITLE
JARs from JitPack

### ISSUE THREAD

**Issue by sadovnikov** [mesos/kibana#3]
Generated on JitPack JAR is very different from locally built one. Attempts to install the framework with JAR from JitPack `https://jitpack.io/com/github/mesos/kibana/_KB_VERSION_/kibana-_KB_VERSION_.jar` fail with `ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean`
The generated on JitPack JARs are not complete

**Comment by sadovnikov** [comment]
Actually, I liked the way Kibana build names JARs. If there are not local changes, its adds commit ID to the jar name; if commit ID matches with tag - it adds tags instead of commit ID; if there are local changes - it adds “local” with timestamp. However this seems to be confusing for JitPack

**Comment by philwinder** [comment]
Fixed in #7

**Comment by sadovnikov** [comment]
resolved by @philwinder
